name: buildtest

on:
  push:
    branches: 
    - main
    - release
    - feat/*
  pull_request:
    branches:
    - main
    - release

jobs:
  build:

    runs-on: macos-latest

    steps:
    
    - uses: actions/checkout@v2
    - name: Install Tuist
      run: curl -Ls https://install.tuist.io|bash

    - name: Setup Xcode version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '14.2.0'
        
    - name: Bring ignored files
      uses: actions/checkout@v3
      with:
        repository: gnksbm/AppStore-ignored
        path: Config/Secrets.xcconfig
        token: ${{ secrets.ACTION_TOKEN }}

    # - name: Install Fastlane
    #   run: brew install fastlane
    
    - name: Tuist clean
      run: tuist clean

    - name: Tuist fetch
      run: tuist fetch

    - name: Tuist generate
      run: tuist generate

    - name: Run Tests
      run: |
        xcodebuild clean test -workspace AppStore.xcworkspace -scheme AppStore -destination 'platform=iOS Simulator,name=iPhone 13 Pro,OS=16.0'
